UI Changes & Critical Bug Fix
FrederoxDev/Amethyst-Launcher pull request #46
Opened 2024-07-07 12:14 UTC by OmniacDev

Fixed a bug where the proxy wasn't able to be located due to recent changes in the bundler

and there's a bunch of UI changes cause I accidentally did them on the same branch :P

2024-07-08 11:06 UTC, FrederoxDev commented on src/renderer/versionSwitcher/AppRegistry.ts
> +    const maxAttempts = 100;
this can be set to like 30 or something

2024-07-08 11:06 UTC, FrederoxDev requested changes
see comment about max attempts. Can I also get screenshots of any UI changes

2024-07-08 11:07 UTC, FrederoxDev commented on src/renderer/versionSwitcher/AppRegistry.ts
> +    const maxAttempts = 100;
If it fails, it would be helpful to display the fix to this in launcher. The solution is pinned in the support channel in the discord rn. At no point though should the launcher automatically do any of it, I want to keep any uninstall steps completely on the end users doing

2024-07-08 11:25 UTC, OmniacDev commented
### **Global UI Changes:**

- Navbar and View containers are now floating
- Background from home page is now applied to the main view container and sits behind all floating containers
- Everything now has 3px borders for consistency

### **Titlebar Changes**: 
- Added a 3px shadow

### **Home Page Changes:**
- Moved background to the main view container

![Screenshot 2024-07-08 231641](https://github.com/FrederoxDev/Amethyst-Launcher/assets/64994204/38b0c9e8-a1f0-4f79-bafa-454edfd8c795)

### **Profiles Page Changes:**
- Improved profile buttons

![Screenshot 2024-07-08 231650](https://github.com/FrederoxDev/Amethyst-Launcher/assets/64994204/baf0a6c4-8244-4870-81ae-3303d1af3ddc)

### **Mods Page Changes:**
- Edited buttons to match those in the Profiles Page

![Screenshot 2024-07-08 231657](https://github.com/FrederoxDev/Amethyst-Launcher/assets/64994204/2e74915d-ad1a-45f0-bdbe-98d12bc89cab)

### **Settings Page Changes:**
- Made settings container scrollable
- Changed the settings section to the correct style

**Other changes:**
- Refactored some of the components, added themes for dark and light mode to the MinecraftRadialButton component.

![Screenshot 2024-07-08 231704](https://github.com/FrederoxDev/Amethyst-Launcher/assets/64994204/d1dd1efc-706b-4092-87d7-e1d1e5560222)
![Screenshot 2024-07-08 231713](https://github.com/FrederoxDev/Amethyst-Launcher/assets/64994204/cbfa48cb-15f4-4663-9a8a-116fc391bd74)

2024-07-08 12:03 UTC, FrederoxDev commented
I noticed that the font for the launcher config debug viewer seems to be wrong

2024-07-08 12:05 UTC, OmniacDev commented
yeah I changed it to be a bit more readable since it could be important

2024-07-08 12:06 UTC, OmniacDev commented
want it changed back?

2024-07-08 12:07 UTC, FrederoxDev commented
Yes please, I dont really find it unreadable at its current state?

2024-07-08 12:14 UTC, OmniacDev commented
Done 👍🏻

2024-07-08 12:22 UTC, OmniacDev commented
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/64994204/9350b0fa-6ee5-4347-8c91-f9991774d8a9)

2024-07-09 09:40 UTC, OmniacDev commented
https://www.youtube.com/watch?v=5xooMXyleXM

2024-07-09 09:40 UTC, OmniacDev commented
oh shit didn't mean to close it

2024-07-10 01:05 UTC, OmniacDev commented
Refactored a lot of the launcher's backend and fixed a few issues.

2024-07-11 05:15 UTC, OmniacDev commented
PR is getting a bit big

2024-07-11 16:05 UTC, OmniacDev commented
### Version Manager

Added Version Manager page which automatically finds versions within Amethyst's AppData folder, and displays them.
Currently there are three buttons;
- Delete version
- Open version folder
- Version info (pretty basic right now, just shows the version folder path)

https://cdn.discordapp.com/attachments/1184966399194570795/1260989327698296932/2024-07-12_04-00-07.mp4?ex=66915353&is=669001d3&hm=22abde1191d2899cb4aed963896528a945236d9286e00e68d02863c8a53e44f1&

2024-07-12 03:22 UTC, OmniacDev commented
# Error Popup UI:
- Improved and added close button

![image](https://github.com/user-attachments/assets/c3fa52b0-7c4d-49ff-9393-b5ae9888e2a0)


# AppRegistry Changes:
- **Unregister Package:** Replaced `PreserveApplicationData` arg with `PreserveRoamableApplicationData`, so that the unregistering doesn't fail when a version from MS Store is installed.

2024-07-12 10:24 UTC, FrederoxDev commented
Ok, well im willing to merge this whenever you're ready, it seems there are some conflicts from another PR

2024-07-12 10:26 UTC, FrederoxDev commented
Also did you remove Ctrl R? just noticed its not working in the launcher anymore.

2024-07-12 12:11 UTC, OmniacDev commented
# Import .ZIP Files and Folders
- Modified and added functionality to drag and drop .zip files and folders into the launcher from PR #45 
- Fixed a lot of stuff in it.

# Error Popup UI
- Made it more generic, and added a warning icon


https://github.com/user-attachments/assets/19a4d559-3f6f-45cc-8d97-7860c9ad2e85

2024-07-12 16:16 UTC, OmniacDev commented
Imma start working on some new stuff on a separate branch so this PR is pretty much done, lmk if it needs any other changes

2024-07-12 16:28 UTC, FrederoxDev commented
i'll test and merge this later on today

2024-07-12 19:20 UTC, merged